#!/usr/bin/env php

<?php

use My\Coded\PHPServer\Request;
use My\Coded\PHPServer\Response;
use My\Coded\PHPServer\Server;



// remove the first item
array_shift($argv);

// if no port defined, then 80
if (empty($argv)) {
    $port = 80;
} else {
    $port = array_shift($argv);
}

require 'vendor/autoload.php';

$server = new Server('127.0.0.1', $port);

$server->listen(function (Request $request) {
    return new Response('<h1>Hello-Server</h1>');
});
